Traceback (most recent call last):
  File "../Datos/Envios/175/ejemplo.py", line 1, in <module>
    n = int(input(""))
ValueError: invalid literal for int() with base 10: '5 6'

real	0m0,055s
user	0m0,045s
sys	0m0,010s
